// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjO2-BGjFjQW1I-i4UnIhnlAgfk6WMcbs',
    appId: '1:1073420775313:web:5d06a4d1d4328afa9af430',
    messagingSenderId: '1073420775313',
    projectId: 'pokedex-flutter-d4cce',
    authDomain: 'pokedex-flutter-d4cce.firebaseapp.com',
    storageBucket: 'pokedex-flutter-d4cce.appspot.com',
    measurementId: 'G-K49B1BF1F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD_-o8-7e-sD5Ov-KLwp20_jrLr_USnqA',
    appId: '1:1073420775313:android:613134a6733c42cc9af430',
    messagingSenderId: '1073420775313',
    projectId: 'pokedex-flutter-d4cce',
    storageBucket: 'pokedex-flutter-d4cce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN4g7DzgSf1psTTrwUGY_9k2WLEZCq0oU',
    appId: '1:1073420775313:ios:435993b3b2c3073f9af430',
    messagingSenderId: '1073420775313',
    projectId: 'pokedex-flutter-d4cce',
    storageBucket: 'pokedex-flutter-d4cce.appspot.com',
    iosClientId: '1073420775313-ftnbh3lmdiamtrgpc1cq4ca3ams3bq6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN4g7DzgSf1psTTrwUGY_9k2WLEZCq0oU',
    appId: '1:1073420775313:ios:87a281ae686f1bea9af430',
    messagingSenderId: '1073420775313',
    projectId: 'pokedex-flutter-d4cce',
    storageBucket: 'pokedex-flutter-d4cce.appspot.com',
    iosClientId: '1073420775313-q0gqska8tenphm399isdq34sifopgoqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile.RunnerTests',
  );
}
